name: Code Review Action

on: 
  pull_request:
    types: [opened, edited, reopened]

jobs:
  prepare_ruby_env:
    name: Prepare Ruby Env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.8'
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install
  code_review:
    name: Code Review
    needs: prepare_ruby_env
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
    run: |
      bundle exec ruby ./.github/workflows/scripts/code_review.rb $GITHUB_TOKEN ${{ github.event.repository.full_name }} ${{ github.event.pull_request.number }} $CHAT_GPT_API_KEY
    shell: bash
    working-directory: .
